sudo: false
language: php
os:
  - linux
php:
  - 7.4
  - nightly
before_script:
  - composer self-update
  - COMPOSER_MEMORY_LIMIT=5G composer install --no-dev --prefer-dist
script: composer run-script test
notifications:
  email: false
branches:
  only:
  - master
